spring:
  datasource:
    url: jdbc:mysql://localhost/freight_transport_region_vehicles
    driverClassName: com.mysql.cj.jdbc.Driver
    username: newuser
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9500